### ISSUE TITLE
컴포넌트 스켈레톤 제작 - svg 커스텀 컴포넌트화

### ISSUE THREAD

**Issue by SeyoungCho** [codeit-bootcamp-frontend/0-crypto-meter-technokings#15]
### Description

- SVG파일들을 효율적으로 사용하기 위해 prop을 받는 컴포넌트로 만드는 작업입니다.

### To-do

- [ ] 기획안을 참고하여 svg파일들을 추출한 후 html 태그를 뽑아냅니다.
- [ ] styled-components를 이용히여 커스텀 svg태그를 만들어 svg태그를 감싸줍니다.
- [ ] 각 svg파일별로 props를 정하고 적용시킵니다.
