### ISSUE TITLE
:white_check_mark: 기능 구현하기 - sns 공유하기 및 차트 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by wooleejaan** [codeit-bootcamp-frontend/0-crypto-meter-technokings#42]
### Description

차트 컴포넌트 기능 구현 및 리팩토링 진행 

### To-do

- [ ] sns 공유하기 (카카오/페이스북 기능 추가) 
- [ ] 차트 컴포넌트 리팩토링 
- [ ] 차트 컴포넌트에 api 추가
