### ISSUE TITLE
:white_check_mark: 기능 구현하기 - 전체 레이아웃 구성 

### ISSUE THREAD

**Issue by wooleejaan** [codeit-bootcamp-frontend/0-crypto-meter-technokings#48]
### Description

각 컴포넌트들을 보여준 메인 페이지 레이아웃 구성 및 차트 컴포넌트 fallback 적용

### To-do

- [ ] 메인 페이지 레이아웃 구성 (부분 스크롤)
- [ ] 차트 컴포넌트 fallback 적용 
- [ ] 그 외 기타 리팩토링 반영
