### ISSUE TITLE
:white_check_mark: 기능 구현하기 - InputBoard에 store연동하기

### ISSUE THREAD

**Issue by SeyoungCho** [codeit-bootcamp-frontend/0-crypto-meter-technokings#49]
### Description

InputBoard 컴포넌트에서 userInputStore에서 필요한 상태들을 구독하여 store와 데이터를 주고 받게 합니다. 

### To-do

- [ ] InputBoard에서 필요한 전역 상태 구독하기
- [ ] InputBoard의 각 컴포넌트에서 필요한 상태 구독하기
- [ ] userInputStore의 set함수를 이용하여 각 자식 컴포넌트에서 상태 변경 액션을 사용하기
