### ISSUE TITLE
:white_check_mark: Gnb 기능 구현

### ISSUE THREAD

**Issue by SeyoungCho** [codeit-bootcamp-frontend/0-crypto-meter-technokings#57]
### Description

Gnb컴포넌트에 기능을 추가합니다.

### To-do

- [x] 초기화 버튼 기능 추가
- [x] 화폐단위 변경 기능 추가
- [x] 검색기록 삭제 및 화폐 단위 기준 필터링 기능 추가
