### ISSUE TITLE
:white_check_mark: 기능 구현하기 - InputBoard api 연동

### ISSUE THREAD

**Issue by SeyoungCho** [codeit-bootcamp-frontend/0-crypto-meter-technokings#66]
### Description

InputBoard에서 오늘은 얼마가 되었을까 버튼 클릭 시 실제 api 요청을 수행하도록 합니다. 

### To-do

- [ ] mock api함수를 실제 axios api함수로 교체하기
- [ ] 선택한 화폐 단위가 변경되면 MoneyInput에 보여지는 단위도 교체
- [ ] IncreaseMoneyButton의 옵션 또한 선택한 화폐단위에 맞게 변경되는 기능 추가
